apiVersion: v1
kind: Service
metadata:
  name: graphshield-api
  namespace: graphshield
spec:
  selector:
    app: graphshield-api
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
